//should prob be somewhere else but eh CBA for now
using System.Collections.Generic;

namespace TimelineAnimator;

public static class BoneNameHelpers
{
    public static string GetDisplayName(string internalName)
    {
        if (BoneNames.TryGetValue(internalName, out var displayName))
        {
            return displayName;
        }
        return internalName;
    }

    private static readonly Dictionary<string, string> BoneNames = new()
    {
        { "n_root", "Root" },
        { "n_hara", "Abdomen" },
        { "n_throw", "Throw" },
        { "j_kosi", "Waist" },
        { "j_sebo_a", "Lumbar" },
        { "j_asi_a_l", "Left Leg" },
        { "j_asi_a_r", "Right Leg" },
        { "j_buki2_kosi_l", "Left Holster" },
        { "j_buki2_kosi_r", "Right Holster" },
        { "j_buki_kosi_l", "Left Sheathe" },
        { "j_buki_kosi_r", "Right Sheathe" },
        { "j_sebo_b", "Thoracic" },
        { "j_sk_b_a_l", "Left Cloth Back A" },
        { "j_sk_b_a_r", "Right Cloth Back A" },
        { "j_sk_f_a_l", "Left Cloth Front A" },
        { "j_sk_f_a_r", "Right Cloth Front A" },
        { "j_sk_s_a_l", "Left Cloth Side A" },
        { "j_sk_s_a_r", "Right Cloth Side A" },
        { "j_asi_b_l", "Left Knee" },
        { "j_asi_b_r", "Right Knee" },
        { "j_mune_l", "Left Breast" },
        { "j_mune_r", "Right Breast" },
        { "j_sebo_c", "Cervical" },
        { "j_sk_b_b_l", "Left Cloth Back B" },
        { "j_sk_b_b_r", "Right Cloth Back B" },
        { "j_sk_f_b_l", "Left Cloth Front B" },
        { "j_sk_f_b_r", "Right Cloth Front B" },
        { "j_sk_s_b_l", "Left Cloth Side B" },
        { "j_sk_s_b_r", "Right Cloth Side B" },
        { "j_asi_c_l", "Left Calf" },
        { "j_asi_c_r", "Right Calf" },
        { "j_buki_sebo_l", "Left Scabbard" },
        { "j_buki_sebo_r", "Right Scabbard" },
        { "j_kubi", "Neck" },
        { "j_sako_l", "Left Clavicle" },
        { "j_sako_r", "Right Clavicle" },
        { "j_sk_b_c_l", "Left Cloth Back C" },
        { "j_sk_b_c_r", "Right Cloth Back C" },
        { "j_sk_f_c_l", "Left Cloth Front C" },
        { "j_sk_f_c_r", "Right Cloth Front C" },
        { "j_sk_s_c_l", "Left Cloth Side C" },
        { "j_sk_s_c_r", "Right Cloth Side C" },
        { "n_hizasoubi_l", "Left Poleyn" },
        { "n_hizasoubi_r", "Right Poleyn" },
        { "j_asi_d_l", "Left Foot" },
        { "j_asi_d_r", "Right Foot" },
        { "j_kao", "Head" },
        { "j_ude_a_l", "Left Arm" },
        { "j_ude_a_r", "Right Arm" },
        { "n_kataarmor_l", "Left Pauldron" },
        { "n_kataarmor_r", "Right Pauldron" },
        { "j_asi_e_l", "Left Toes" },
        { "j_asi_e_r", "Right Toes" },
        { "j_kami_a", "Hair A" },
        { "j_kami_f_l", "Left Hair Front" },
        { "j_kami_f_r", "Right Hair Front" },
        { "j_mimi_l", "Left Ear" },
        { "j_mimi_r", "Right Ear" },
        { "j_ude_b_l", "Left Forearm" },
        { "j_ude_b_r", "Right Forearm" },
        { "n_hkata_l", "Left Shoulder (Twist)" },
        { "n_hkata_r", "Right Shoulder (Twist)" },
        { "j_kami_b", "Hair B" },
        { "j_te_l", "Left Hand" },
        { "j_te_r", "Right Hand" },
        { "n_buki_tate_l", "Left Shield" },
        { "n_buki_tate_r", "Right Shield" },
        { "n_ear_a_l", "Left Earring A" },
        { "n_ear_a_r", "Right Earring A" },
        { "n_hhiji_l", "Left Elbow (Twist)" },
        { "n_hhiji_r", "Right Elbow (Twist)" },
        { "n_hijisoubi_l", "Left Couter" },
        { "n_hijisoubi_r", "Right Couter" },
        { "n_hte_l", "Left Wrist" },
        { "n_hte_r", "Right Wrist" },
        { "j_hito_a_l", "Left Index A" },
        { "j_hito_a_r", "Right Index A" },
        { "j_ko_a_l", "Left Pinky A" },
        { "j_ko_a_r", "Right Pinky A" },
        { "j_kusu_a_l", "Left Ring A" },
        { "j_kusu_a_r", "Right Ring A" },
        { "j_naka_a_l", "Left Middle A" },
        { "j_naka_a_r", "Right Middle A" },
        { "j_oya_a_l", "Left Thumb A" },
        { "j_oya_a_r", "Right Thumb A" },
        { "n_buki_l", "Left Weapon" },
        { "n_buki_r", "Right Weapon" },
        { "n_ear_b_l", "Left Earring B" },
        { "n_ear_b_r", "Right Earring B" },
        { "j_hito_b_l", "Left Index B" },
        { "j_hito_b_r", "Right Index B" },
        { "j_ko_b_l", "Left Pinky B" },
        { "j_ko_b_r", "Right Pinky B" },
        { "j_kusu_b_l", "Left Ring B" },
        { "j_kusu_b_r", "Right Ring B" },
        { "j_naka_b_l", "Left Middle B" },
        { "j_naka_b_r", "Right Middle B" },
        { "j_oya_b_l", "Left Thumb B" },
        { "j_oya_b_r", "Right Thumb B" },
        { "n_sippo_a", "Tail A" },
        { "n_sippo_b", "Tail B" },
        { "n_sippo_c", "Tail C" },
        { "n_sippo_d", "Tail D" },
        { "n_sippo_e", "Tail E" },
        { "j_ago", "Jaw" },
        { "j_f_dmab_l", "Left Lower Eyelid" },
        { "j_f_dmab_r", "Right Lower Eyelid" },
        { "j_f_eye_l", "Left Eye" },
        { "j_f_eye_r", "Right Eye" },
        { "j_f_hana", "Nose" },
        { "j_f_lip_l", "Left Lips" },
        { "j_f_lip_r", "Right Lips" },
        { "j_f_memoto", "Bridge" },
        { "j_f_miken_l", "Left Brow" },
        { "j_f_miken_r", "Right Brow" },
        { "j_f_ulip_a", "Upper Lip A" },
        { "j_f_umab_l", "Left Upper Eyelid" },
        { "j_f_umab_r", "Right Upper Eyelid" },
        { "j_f_dlip_a", "Lower Lip A" },
        { "j_f_ulip_b", "Upper Lip B" },
        { "j_f_dlip_b", "Lower Lip B" },
        { "j_zera_a_l", "Left Ear 1A" },
        { "j_zera_a_r", "Right Ear 1A" },
        { "j_zera_b_l", "Left Ear 1B" },
        { "j_zera_b_r", "Right Ear 1B" },
        { "j_zerb_a_l", "Left Ear 2A" },
        { "j_zerb_a_r", "Right Ear 2A" },
        { "j_zerb_b_l", "Left Ear 2B" },
        { "j_zerb_b_r", "Right Ear 2B" },
        { "j_zerc_a_l", "Left Ear 3A" },
        { "j_zerc_a_r", "Right Ear 3A" },
        { "j_zerc_b_l", "Left Ear 3B" },
        { "j_zerc_b_r", "Right Ear 3B" },
        { "j_zerd_a_l", "Left Ear 4A" },
        { "j_zerd_a_r", "Right Ear 4A" },
        { "j_zerd_b_l", "Left Ear 4B" },
        { "j_zerd_b_r", "Right Ear 4B" },
        { "j_f_hige_l", "Left Whiskers" },
        { "j_f_hige_r", "Right Whiskers" },
        { "j_f_uago", "Upper Lip A" },
        { "j_f_ulip", "Upper Lip B" },
        { "n_f_lip_l", "Left Lips" },
        { "n_f_lip_r", "Right Lips" },
        { "n_f_ulip_l", "Left Upper Lip" },
        { "n_f_ulip_r", "Right Upper Lip" },
        { "j_f_dlip", "Lower Lip" },
        { "j_ex_met_va", "Visor" },
        { "mh_n_hara", "Main Hand" },
        { "oh_n_hara", "Off Hand" },
        { "j_half_l", "Left Half" },
        { "j_half_r", "Right Half" },
        { "j_f_ago", "Jaw" },
        { "j_f_dago", "Lower Jaw" },
        { "j_f_bero_01", "Tongue A" },
        { "j_f_bero_02", "Tongue B" },
        { "j_f_bero_03", "Tongue C" },
        { "j_f_hagukiup", "Upper Teeth" },
        { "j_f_hagukidn", "Lower Teeth" },
        { "j_f_dlip_01_l", "Lip Lower Left Center A" },
        { "j_f_dlip_02_l", "Lip Lower Left Center B" },
        { "j_f_dlip_01_r", "Lip Lower Right Center A" },
        { "j_f_dlip_02_r", "Lip Lower Right Center B" },
        { "j_f_ulip_01_l", "Lip Upper Left Center A" },
        { "j_f_ulip_02_l", "Lip Upper Left Center B" },
        { "j_f_ulip_01_r", "Lip Upper Right Center A" },
        { "j_f_ulip_02_r", "Lip Upper Right Center B" },
        { "j_f_dmlip_01_l", "Lip Lower Left A" },
        { "j_f_dmlip_02_l", "Lip Lower Left B" },
        { "j_f_dmlip_01_r", "Lip Lower Right A" },
        { "j_f_dmlip_02_r", "Lip Lower Right B" },
        { "j_f_umlip_01_l", "Lip Upper Left A" },
        { "j_f_umlip_02_l", "Lip Upper Left B" },
        { "j_f_umlip_01_r", "Lip Upper Right A" },
        { "j_f_umlip_02_r", "Lip Upper Right B" },
        { "j_f_uslip_l", "Lip Upper Left Corner A" },
        { "j_f_dslip_l", "Lip Lower Left Corner A" },
        { "j_f_uslip_r", "Lip Upper Right Corner A" },
        { "j_f_dslip_r", "Lip Lower Right Corner A" },
        { "j_f_mab_l", "Left Eye Socket" },
        { "j_f_mab_r", "Right Eye Socket" },
        { "j_f_eyepuru_l", "Left Iris" },
        { "j_f_eyepuru_r", "Right Iris" },
        { "j_f_mabup_01_l", "Left Upper Eyelid" },
        { "j_f_mabdn_01_l", "Left Lower Eyelid" },
        { "j_f_mabup_01_r", "Right Upper Eyelid" },
        { "j_f_mabdn_01_r", "Right Lower Eyelid" },
        { "j_f_mabup_02out_l", "Left Upper Eyelid Outer" },
        { "j_f_mabdn_02out_l", "Left Lower Eyelid Outer" },
        { "j_f_mabup_03in_l", "Left Upper Eyelid Inner" },
        { "j_f_mabdn_03in_l", "Left Lower Eyelid Inner" },
        { "j_f_mabup_02out_r", "Right Upper Eyelid Outer" },
        { "j_f_mabdn_02out_r", "Right Lower Eyelid Outer" },
        { "j_f_mabup_03in_r", "Right Upper Eyelid Inner" },
        { "j_f_mabdn_03in_r", "Right Lower Eyelid Inner" },
        { "j_f_mayu_l", "Left Eyebrow A" },
        { "j_f_mayu_r", "Right Eyebrow A" },
        { "j_f_mmayu_l", "Left Eyebrow B" },
        { "j_f_mmayu_r", "Right Eyebrow B" },
        { "j_f_miken_01_l", "Left Brow Ridge A" },
        { "j_f_miken_02_l", "Left Brow Ridge B" },
        { "j_f_miken_01_r", "Right Brow Ridge A" },
        { "j_f_miken_02_r", "Right Brow Ridge B" },
        { "j_f_face", "Face" },
        { "j_f_hoho_l", "Left Cheek" },
        { "j_f_hoho_r", "Right Cheek" },
        { "j_f_dhoho_l", "Left Outer Cheek" },
        { "j_f_dhoho_r", "Right Outer Cheek" },
        { "j_f_shoho_l", "Left Middle Cheek" },
        { "j_f_shoho_r", "Right Middle Cheek" },
        { "j_f_dmemoto_l", "Left Inner Cheek" },
        { "j_f_dmemoto_r", "Right Inner Cheek" },
        { "j_f_uhana", "Bridge" },
        { "j_f_hana_l", "Left Nostril" },
        { "j_f_hana_r", "Right Nostril" },
        { "j_f_dmiken_l", "Left Glabella" },
        { "j_f_dmiken_r", "Right Glabella" },
        { "j_ex_met_vb", "Visor" },
    };
}